#!/usr/bin/env bash
#
# vim: set foldmethod=marker:
#
# execute sudo after copying over MIT-magic-cookie
# and making $SSH_AUTH_SOCK accessible.
#
# Author: Jan Jaeger
#

# These environment variables will be carried over
preserve_env="GIT_AUTHOR_EMAIL,GIT_AUTHOR_NAME,GIT_COMMITTER_EMAIL,GIT_COMMITTER_NAME"

# {{{ Binaries
which=$( which which )       ; [[ -z ${which} ]]    && echo "which not found." && exit 1
basename=$( which basename ) ; [[ -z ${basename} ]] && echo "basename not found." && exit 1
id=$( $which id )            ; [[ -z ${id} ]]       && echo "id not found." && exit 1
sudo=$( $which sudo )        ; [[ -z ${sudo} ]]     && echo "sudo not found." && exit 1
# }}}

# {{{ Functions
usage() {
    echo "$(${basename} "$0"): execute sudo after copying over MIT-magic-cookie and/or making \$SSH_AUTH_SOCK available."
    echo "usage: $0 [-ax] [sudo options|command]"
    echo "options:"
    echo "-a        make current user's ssh auth socket accessible after sudo and create link to it."
    echo "-x        copy over current user's MIT-magic-cookie."
    echo "Options may only be given with ONE dash: -x, -ax, etc. All following options will be considered options to sudo."
    echo "An example would be: xudo -a -iu ansible. Here -a is an option to xudo, -iu are options to sudo meaning perform"
    echo "a login as user ansible."
    exit 0
}
# }}}

if [[ $# -eq 0 ]] ; then
    usage
    exit 0
fi

case $1 in
    -a)
    do_agent_forwarding="true"
    shift
    ;;
    -x)
    do_X_forwarding="true"
    shift
    ;;
    -ax|-xa)
    do_agent_forwarding="true"
    do_X_forwarding="true"
    shift
    ;;
    -h|-?)
    usage
    exit 0
    ;;
esac

i=$(( $# - 1 ))
while [[ ${i} -ge 0 ]] ; do
    token=${BASH_ARGV[$i]}
    #echo "i=$i: $token"
    if [[ ${token} =~ ^-[a-zA-Z]*u ]] ; then
        (( i-=1 ))
        sudo_user=${BASH_ARGV[$i]}
    fi
    if [[ "x${token}" == "xsu" ]] ; then
        if [[ "x${BASH_ARGV[0]}" == "x-" ]] || [[ ${i} -eq 0 ]] ; then
            target_user="root"
        elif ${id} ${BASH_ARGV[0]} >/dev/null 2>&1 ; then
            target_user=${BASH_ARGV[0]}
        fi
        break
    fi
    (( --i ))
done
target_user=${target_user-${sudo_user}}
target_user=${target_user-root}
if ! ${id} ${target_user} >/dev/null 2>&1 ; then
    echo "target user does not exist. exiting."
    exit 1
fi

if [[ "x${do_X_forwarding}" == "xtrue" ]] ; then
    xauth=$( ${which} xauth )    ; [[ -z ${xauth} ]]    && echo "xauth not found." && exit 1
    cookie=$( ${xauth} list "${DISPLAY}" )
    ${sudo} -u ${target_user} -i ${xauth} add ${cookie} 2>/dev/null
    # DISPLAY magically shows up on it's own
    #preserve_env="${preserve_env+${preserve_env},}${DISPLAY}"
fi

if [[ "x${do_agent_forwarding}" == "xtrue" && ! -z "${SSH_AUTH_SOCK}" ]] ; then
    setfacl=$( $which setfacl )  ; [[ -z ${setfacl} ]]  && echo "setfacl not found." && exit 1
    ssh_auth_sock="${SSH_AUTH_SOCK}"

    # remove stale sessions
    find /tmp/xudo-* -maxdepth 0 > /dev/null 2>&1 &&
        find /tmp/xudo-* -name sudo.pid -user $USER -exec sh -c 'ps -p $(cat {}) > /dev/null || rm -r $(dirname {})' \;

    {
        while ps -p $$ > /dev/null 2>&1 ; do 
            sleep 5
        done
        find /tmp/xudo-* -maxdepth 0 > /dev/null 2>&1 &&
          find /tmp/xudo-* -name sudo.pid -user $USER -exec sh -c 'ps -p $(cat {}) > /dev/null || rm -r $(dirname {})' \;
    } &

    xudo_tmpdir=$( mktemp -td xudo-XXXXXXXXXX )
    target_user_ssh_auth_sock="${xudo_tmpdir}/agent.sock"
    ln -s ${ssh_auth_sock} ${target_user_ssh_auth_sock}
    echo $$ > ${xudo_tmpdir}/sudo.pid
    echo ${target_user} > ${xudo_tmpdir}/sudo.user

    if [[ $(uname) == "FreeBSD" ]] ; then
        ${setfacl} -m u:${target_user}:rwxp::allow "${ssh_auth_sock}"
    else
        ${setfacl} -m u:${target_user}:rwx "${ssh_auth_sock}"
    fi
    sock_dir="$( dirname "${ssh_auth_sock}" )"
    if [[ ! "x${sock_dir}" == "x${HOME}/.ssh" ]] ; then
        if [[ $(uname) == "FreeBSD" ]] ; then
            ${setfacl} -m u:${target_user}:rxp::allow "${sock_dir}"
        else
            ${setfacl} -m u:${target_user}:rx "${sock_dir}"
            ${setfacl} -m u:${target_user}:rx ${xudo_tmpdir}
        fi
    fi
    SSH_AUTH_SOCK="${target_user_ssh_auth_sock}"
    preserve_env="${preserve_env+"${preserve_env},"}SSH_AUTH_SOCK"
fi

preserve_env="${preserve_env+"--preserve-env=${preserve_env}"}"
#echo "$preserve_env"
exec ${sudo} ${preserve_env} "$@"
